import React from 'react';
import $ from 'jquery';

import TimeSlotList from './timeSlotList';
//import TimeSlotForm from './timeSlotForm';

import { API_URL, POLL_INTERVAL } from './global';

module.exports = React.createClass({
  loadTimeSlotsFromServer: function() {
    $.ajax({
      url: API_URL,
      dataType: 'json',
      cache: false,
      success: function(data) {
        this.setState({data: data});
      }.bind(this),
      error: function(xhr, status, err) {
        console.error(API_URL, status, err.toString());
      }.bind(this)
    });
  },
  handleTimeSlotSubmit: function(timeSlot) {
    var timeSlots = this.state.data;
    // Optimistically set an id on the new time slot. It will be replaced by an
    // id generated by the server. In a production application you would likely
    // not use Date.now() for this and would have a more robust system in place.
    timeSlot.id = Date.now();
    var newTimeSlots = timeSlots.concat([timeSlot]);
    this.setState({data: newTimeSlots});
    $.ajax({
      url: API_URL,
      dataType: 'json',
      type: 'PUT',
      data: timeSlot,
      success: function(data) {
        this.setState({data: data});
      }.bind(this),
      error: function(xhr, status, err) {
        //this.setState({data: timeSlots});
        console.error(API_URL, status, err.toString());
      }.bind(this)
    });
  },
  getInitialState: function() {
    return {data: []};
  },
  componentDidMount: function() {
    this.loadTimeSlotsFromServer();
    setInterval(this.loadTimeSlotsFromServer, POLL_INTERVAL);
  },
  render: function() {
    return (
      <div className="timeSlotBox">
        <h1>Signup Times</h1>
        <TimeSlotList data={this.state.data} onTimeSlotSubmit={this.handleTimeSlotSubmit} />
      </div>
    );
  }
});
